name: Auto-generate yaml & list files

on:
  schedule:
    - cron: "0 0 * * *"  # каждый день в 00:00 UTC / 03:00 МСК
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем текущий репозиторий
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: files  # работаем с веткой files

      - name: Загружаем и преобразуем списки
        run: |
          # Папки для результатов
          mkdir -p yaml_config list_config

          # Массив входных файлов
          FILES=(
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Russia/inside-raw.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/youtube.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/discord.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/discord.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/meta.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/twitter.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/google_ai.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/google_play.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/Meta.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv4/twitter.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv6/Discord.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv6/Meta.lst"
            "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Subnets/IPv6/Twitter.lst"
          )

          for url in "${FILES[@]}"; do
            # Имя файла и родительская папка
            base=$(basename "$url" .lst)
            parent=$(basename "$(dirname "$url")")
            name="${parent}_${base}"

            echo "Обрабатываем $url → $name"

            # === YAML для Clash ===
            {
              echo "payload:"
              curl -sSL "$url" \
                | grep -v '^\s*$' \
                | sed 's/^\(\.\)/  - +\1/; t; s/^/  - +./'
            } > "yaml_config/${name}.yaml"

            # === LIST для Shadowrocket ===
            curl -sSL "$url" \
              | grep -v '^\s*$' \
              | while read line; do
                  if echo "$line" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/'; then
                    # IPv4
                    echo "IP-CIDR,$line"
                  elif echo "$line" | grep -Eq '^([0-9a-fA-F:]+)+/'; then
                    # IPv6
                    echo "IP-CIDR,$line"
                  else
                    # домен
                    clean=$(echo "$line" | sed 's/^\.//')
                    echo "DOMAIN-SUFFIX,$clean"
                  fi
                done > "list_config/${name}.list"
          done

      - name: Коммитим изменения в ветку files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add yaml_config/*.yaml list_config/*.list

          if git diff --cached --quiet; then
            echo "Файлы не изменились — пропускаем коммит."
          else
            git commit -m "Auto-update configs on $(TZ='Europe/Moscow' date '+%Y-%m-%d %H:%M:%S') MSK"
            git push origin files
